import bcrypt from "bcryptjs";

const data = {
    users: [
        {
            name: "Ankel",
            email: "admin@example.com",
            password: bcrypt.hashSync("1234", 8),
            isAdmin: true,
        },
        {
            name: "Paidi",
            email: "paidi@example.com",
            password: bcrypt.hashSync("1234", 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: "Red Flower Dres",
            category: "Dresses",
            image: "/images/p1.jpg",
            price: 30,
            countInStock: 7,
            brand: "Top g",
            rating: 2,
            numReviews: 10,
            description: "Wonderfull red dress with white flowers.",
        },
        {
            name: "Blue dress",
            category: "Dresses",
            image: "/images/p2.jpg",
            price: 55,
            countInStock: 15,
            brand: "Top g",
            rating: 5,
            numReviews: 20,
            description: "Pretty blue dress for parties",
        },
        {
            name: "Denim Shorts",
            category: "Shorts",
            image: "/images/p3.jpg",
            price: 20,
            countInStock: 16,
            brand: "Top g",
            rating: 4,
            numReviews: 8,
            description: "Classic denim shorts for the summer",
        },
        {
            name: "White Corset",
            category: "Corset",
            image: "/images/p4.jpg",
            price: 25,
            countInStock: 3,
            brand: "Top g",
            rating: 4,
            numReviews: 21,
            description: "Beautiful white corset for serius events",
        },
        {
            name: "Denim Pants",
            category: "Pants",
            image: "/images/p5.jpg",
            price: 35,
            countInStock: 12,
            brand: "Top g",
            rating: 5,
            numReviews: 17,
            description: "Denim pants straight from the 80s",
        },
        {
            name: "Flower Skirt",
            category: "Skirts",
            image: "/images/p6.jpg",
            price: 15,
            countInStock: 0,
            brand: "Top g",
            rating: 3.5,
            numReviews: 12,
            description: "Stylish flower skirt for all ages",
        },
    ],
};

export default data;
