const data = {
  products: [
    {
      _id: "1",
      name: "Red Flower Dress",
      category: "Dresses",
      image: "/images/p1.jpg",
      price: 20,
      countInStock: 7,
      brand: "Top g",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Blue dress",
      category: "Dresses",
      image: "/images/p2.jpg",
      price: 25,
      countInStock: 15,
      brand: "Top g",
      rating: 5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Denim Shorts",
      category: "Shorts",
      image: "/images/p3.jpg",
      price: 15,
      countInStock: 16,
      brand: "Top g",
      rating: 4,
      numReviews: 8,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "White Corset",
      category: "Corset",
      image: "/images/p4.jpg",
      price: 30,
      countInStock: 3,
      brand: "Top g",
      rating: 4,
      numReviews: 21,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Denim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 30,
      countInStock: 12,
      brand: "Top g",
      rating: 5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Flower Skirt",
      category: "Skirts",
      image: "/images/p6.jpg",
      price: 29,
      countInStock: 0,
      brand: "Top g",
      rating: 3.5,
      numReviews: 12,
      description: "high quality product",
    },
  ],
};

export default data;
